export const ADD_COMMENT = "ADD_COMMENT";
export const CAMPSITES_LOADING = "CAMPSITES_LOADING"; //loading from server
export const CAMPSITES_FAILED = "CAMPSITES_FAILED"; //failed to load from server
export const ADD_CAMPSITES = "ADD_CAMPSITES"; //action to take once campsites have successfully loaded
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const ADD_PROMOTIONS = "ADD_PROMOTIONS";
export const PROMOTIONS_FAILED = "PROMOTIONS_FAILED";
export const PROMOTIONS_LOADING = "PROMOTIONS_LOADING";
